/** English copy copied from apps/web/messages/en.json (attendance + common.loading). */
export const copy = {
  loading: 'Loading...',
  tabs: {
    overview: 'Overview',
    records: 'Records',
    employees: 'Employees',
  },
  dateFilter: {
    label: 'Date range',
    today: 'Today',
    yesterday: 'Yesterday',
    thisWeek: 'This week',
    thisMonth: 'This month',
    from: 'From',
    to: 'To',
  },
  punchTypes: {
    unknown: 'Unknown',
    entry_on_time: 'On time',
    entry_late: 'Late entry',
    exit: 'Exit',
    early_exit: 'Early exit',
    out_of_shift: 'Out of shift',
  },
  overview: {
    loadError: 'Unable to load attendance overview.',
    employees: 'Employees',
    employeesFooter: 'Registered and punch-only IDs',
    todayPresent: 'Present today',
    todayPresentFooter: (total: number) => `Out of ${total} employees`,
    todayLate: 'Late today',
    attendanceRate: 'Attendance rate',
    attendanceRateFooter: 'Today',
  },
  records: {
    loadError: 'Unable to load attendance records.',
    search: 'Search',
    searchPlaceholder: 'Search by name or ID...',
    employee: 'Employee',
    date: 'Date',
    time: 'Time',
    type: 'Type',
    device: 'Device',
    empty: 'No punches found for this period.',
  },
  employees: {
    loadError: 'Unable to load employees.',
    deviceUserId: 'Device user ID',
    name: 'Name',
    search: 'Search',
    searchPlaceholder: 'Search by name or ID...',
    empty: 'No employees found.',
  },
  logout: 'Log out',
} as const;
